---
title: "WritingExercise05"
---

# Reflect on your own skills and development as a writer

- What are the areas you think you are good at? Where can you improve? -- I can turn texts concise, but i struggle at reading time to time, because my head is elsewhere.

- How will you further develop your skills over the coming year? Can you make a specific, detailed plan? -- Learn the conventions of specific writing styles, within context, erm i am bad at planning, but I will do so by writing more and reading more.

# Reflect on writing more generally

- What principles of composition discussed today did you find most useful? The different types of format in writing proteins, genus, genes

- If you were going to formulate your own writing rules, what would they be? Dont be so difficult about less or fewer or which or that, as the reader understands what you mean, in this day and age. 

# Commit your reflections to writing -- I enjoy writing, but I believe I am terrible writer

Compose a paragraph summarizing your reflections. Remember to use the "commit" process to save your changes when you are finished.

I learnt that I there were far more rules to writing than I thought, which was certainly cool to learn about as it highlighted my ignorence in the english language. When I write typically iw ant to perfect things to the best of y abilities so i will definitely learn all the rules.
